---
galaxy_info:
  author: Sean Sullivan
  description: Excecution enviroment builder
  company: Red Hat

  license: license (MIT)

  min_ansible_version: 2.11
  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - 8
        - 9

  galaxy_tags: []

dependencies: []
...
